# Generated by Django 5.2.3 on 2026-03-18 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_category_alter_blog_image_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='layout',
            field=models.CharField(choices=[('main_thumbs', '1 large + 3 thumbnails'), ('grid', '2 x 2 grid'), ('hero_text', 'Hero image + text')], default='main_thumbs', max_length=20),
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogs/multi/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='myapp.blog')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
