# Generated by Django 5.2.3 on 2026-03-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_blog_layout_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='layout',
            field=models.CharField(choices=[('main_thumbs', '1 large + 3 thumbnails'), ('grid', '2 x 2 grid'), ('hero_text', 'Hero image + text'), ('step_by_step', 'Step by Step')], default='main_thumbs', max_length=20),
        ),
    ]
