# Generated by Django 6.0.3 on 2026-03-18 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_blog_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_steps/')),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='myapp.blog')),
            ],
        ),
    ]
