# Generated by Django 5.2.3 on 2026-03-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_blogcomment_bloglike'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cook_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='prep_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='servings',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
