# Generated by Django 5.2.3 on 2026-03-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_blog_cook_time_blog_ingredients_blog_prep_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_steps/'),
        ),
    ]
